name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

jobs:
  floating-dependencies:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - run: npm i -g npm@7
      - run: npm install --no-package-lock
      - run: npm run test:ember
      - run: npm run test:node

  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: mansona/npm-lockfile-version@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - run: npm i -g npm@7
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ember


  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mansona/npm-lockfile-version@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm i -g npm@7 @lhci/cli@0.5.x
      - run: npm ci
      - run: npm run build && lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: 'test'

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-release
          - ember-data-latest
          - ember-beta
          - ember-canary
          - ember-classic
          - ember-default-with-jquery
          - no-deprecations
          - ember-release-no-deprecations

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
      - run: npm i -g npm@7
      - run: npm ci
      - name: test
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
